### ISSUE TITLE
Unable to access the controller configuration profile on steam

### ISSUE THREAD

**Issue by wachuwamekil** [robinsch/ControllerMod335#10]
When accessing the URL "steam://controllerconfig/3255281634/3069784775" on the deck it displays a weird image.  It acts as though it knows something should be there but just shows a picture of the deck.  (To get the link to my account I had to send it via chat so I could click on it in the steam client.

Browsing to a known good controller share it pulls the expected information.

**Comment by wachuwamekil** [comment]
If you want to just send over a screenshot of the configuration I'm happy to recreate it, just lmk.

**Comment by robinsch** [comment]
https://i.gyazo.com/e4492b0812555a3e4f5834346b413396.png

Sadly my steam language is german so you might need to translate it

**Comment by wachuwamekil** [comment]
That is no problem I can work with that.  I'll send an image once I get the profile updated and shared out!
